#!/usr/bin/env python3
"""
ODM Core — Shared Extraction Library
=====================================
Shared functions used by all ODM parser skills:
  - odm-defaults   (interview attribute rules → Defaults CSV)
  - odm-validations (validationResponse rules → Validations CSV)
  - odm-instructions (carrier submission mapping rules → Instructions CSV) [future]

DO NOT EDIT this file to fix a skill-specific bug.
If the bug is in flag parsing, condition extraction, dead rule detection,
or LOB extraction → fix it here once and all skills benefit.
If the bug is in how defaults are extracted or how validation errors are read
→ fix it in the skill-specific script (odm_defaults.py / odm_validations.py).

Functions exported:
  read_odm_file(filepath)                    → str
  should_skip_file(content, config)          → bool
  extract_flags(content, config)             → (flow, sources, ba_flags_raw, unknown_flags)
  extract_lobs(content, config)              → (includes, excludes)
  extract_conditions(content)                → str
  simplify_conditions(conditions)            → str
  load_config(path)                          → dict
  save_config(config, path)                  → None
  write_csv(df, path)                        → None

Version history:
  V2 — Dead rule detection replaced with logical evaluator (no regex '\band false\)')
       Flow classification reads IS ENABLED direction, not just flag name
"""

import re, json, os
import pandas as pd

# ── Condition Simplifications ─────────────────────────────────────────────────

CONDITION_SIMPLIFICATIONS = [
    (r'Lobses contain (\w+)',        r'LOB = \1'),
    (r'Lobses do not contain (\w+)', r'LOB != \1'),
    (r'is one of \{([^}]+)\}',       lambda m: 'in [' + ', '.join(v.strip().strip('"') for v in m.group(1).split(',')) + ']'),
    (r'(\w+)\s+\.\s+(\w+)',          r'\1.\2'),
    (r'is not unknown',              'is known'),
    (r'all of the following conditions are true\s*:', ''),
    (r'one of the following conditions is true\s*:',  ''),
    (r'\s*-\s*\d+\s+is\s+more\s+than\s+-?\d+',       ''),
    (r'  +', ' '),
]

def simplify_conditions(conditions: str) -> str:
    if not conditions or conditions == 'true':
        return conditions
    result = conditions
    for pattern, replacement in CONDITION_SIMPLIFICATIONS:
        result = re.sub(pattern, replacement, result)
    result = re.sub(r'^\s*[\-\:]\s*', '', result).strip()
    result = re.sub(r'\s*,\s*$', '', result).strip()
    return result if result else conditions


# ── File Reading ──────────────────────────────────────────────────────────────

def read_odm_file(filepath: str) -> str:
    """
    IBM ODM generates UTF-16 LE encoded files on Windows. Falls back to UTF-8.
    Validates decoded content by checking for known ODM markers ('package' or
    'ORIGINAL_BAL') to avoid false positives from BOM-like byte sequences in
    UTF-8 files.
    """
    with open(filepath, 'rb') as f:
        raw = f.read()
    for enc in ['utf-16', 'utf-16-le', 'utf-8']:
        try:
            content = raw.decode(enc)
            if len(content) > 50 and ('package' in content or 'ORIGINAL_BAL' in content):
                return content
        except Exception:
            continue
    raise ValueError(f"Could not decode: {filepath}")


# ── Logical Dead Rule Evaluator ───────────────────────────────────────────────

def _extract_bal_lines(bal_text: str) -> list:
    """
    Extract clean lines from the ORIGINAL_BAL comment block.
    Strips comment markers (* at line start) and blank lines.
    Stops at 'then' keyword.
    """
    lines = []
    for line in bal_text.split('\n'):
        clean = re.sub(r'^\s*\*[\s\t]*', '', line).strip()
        clean = re.sub(r'^\\t+', '', clean).strip()
        if not clean:
            continue
        if re.search(r'\bthen\b', clean):
            break
        lines.append(clean)
    return lines


def _condition_block_has_literal_false(bal_text: str) -> bool:
    """
    Logical evaluator for dead rule detection.

    Parses the BAL condition block and determines whether any AND branch
    contains a literal boolean 'false' value — which short-circuits the
    entire condition to false, making the rule permanently dead.

    Key distinction:
      'SomeField is false'  → live boolean field check — NOT a dead rule
      'and false'           → literal false in AND chain — dead rule
      'true and false'      → literal false in AND chain — dead rule
      'IS ENABLED is false' → feature flag check — NOT a dead rule

    V2 fix: strips all legitimate 'is false' patterns before checking for
    standalone 'and false' — prevents 'SomeField is false' from being
    mistaken for a dead rule marker. This was the regression in V1.
    """
    lines = _extract_bal_lines(bal_text)

    for line in lines:
        # Remove all legitimate 'is false' patterns — field checks and flag checks
        stripped = re.sub(r'\w[\w./\s]*is\s+false', '', line, flags=re.IGNORECASE)

        # Bare 'and false' remaining after stripping → dead rule
        if re.search(r'\band\s+false\b', stripped, re.IGNORECASE):
            return True

        # Line is just 'false' — extremely rare but valid dead marker
        if line.strip().lower() == 'false':
            return True

    return False


# ── Skip-Flag Check ───────────────────────────────────────────────────────────

def should_skip_file(content: str, config: dict) -> bool:
    """
    Return True if this entire rule file should be excluded from output.

    Reasons:
      - fieldId targets a SectionClaim (UI divider, not a real field)
      - fieldId targets a CustomField marked 'skip' in config
      - File contains a skip_flag (ViewMode, DataDictionary, dead A/B tests)
      - ORIGINAL_BAL condition block is always-false (dead rule)

    For skip_flags with always_on=True: only skip when IS ENABLED=false
    (the IS ENABLED=true branch is kept — it still fires).
    """
    if 'SectionClaim/' in content:
        return True

    fm = re.search(r'fieldId\s*=\s*"PolicyData/([^"]+)"', content)
    if fm and fm.group(1).startswith('CustomFields/'):
        field_short = fm.group(1).split('/')[-1]
        routing = config.get('review_later', {}).get('custom_fields', {}).get(field_short)
        if routing == 'skip':
            return True

    skip_cfg = config.get('skip_flags', {})
    for m in re.finditer(r'isInFeature\("([^"]+)"', content):
        flag_name = m.group(1).strip()
        if flag_name in skip_cfg:
            sf = skip_cfg[flag_name]
            if sf.get('always_on') is True:
                enabled_m = re.search(
                    rf'THE FEATURE "{re.escape(flag_name)}" IS ENABLED IN features is (true|false)', content)
                if enabled_m and enabled_m.group(1) == 'false':
                    return True
            else:
                return True

    bal = re.search(r'<ORIGINAL_BAL(.+?)ORIGINAL_BAL>', content, re.DOTALL)
    if bal and _condition_block_has_literal_false(bal.group(1)):
        return True

    return False


# ── Flag Extraction ───────────────────────────────────────────────────────────

def extract_flags(content: str, config: dict) -> tuple:
    """
    Extract and classify all feature flags from file content.
    Returns: (flow, sources, ba_flags_raw, unknown_flags)

    Flow classification — reads BOTH flag name AND IS ENABLED direction (V2 fix):
      Claim:InterviewFlowType_Agent    IS ENABLED = true  → Agent
      Claim:InterviewFlowType_Agent    IS ENABLED = false → Consumer
      Claim:InterviewFlowType_Consumer IS ENABLED = true  → Consumer
      Claim:InterviewFlowType_Consumer IS ENABLED = false → Agent
      Both present → Both

    ba_ flag firing logic:
      always_on=True  + IS ENABLED=true  → fires (ACTIVE)
      always_on=True  + IS ENABLED=false → never fires (INACTIVE) → file skipped
      always_on=False + IS ENABLED=false → fires (ACTIVE)
      always_on=False + IS ENABLED=true  → never fires (INACTIVE) → file skipped
      always_on=None  → source-dependent, included with SOURCE-DEPENDENT label
    """
    claim_cfg  = config.get('claim_flags', {})
    ba_cfg     = config.get('business_flags', {})
    interp_cfg = config.get('source_flags', {}).get('interpretation', {})

    flow_signals = set()
    sources, ba_flags_raw, unknown = [], [], []

    for m in re.finditer(r'isInFeature\("([^"]+)"', content):
        flag = m.group(1).strip()

        if flag.startswith('Claim:'):
            if flag in claim_cfg:
                c = claim_cfg[flag]
                if c.get('category') == 'section':
                    continue
                if c['category'] == 'flow':
                    enabled_m = re.search(
                        rf'THE FEATURE "{re.escape(flag)}" IS ENABLED IN features is (true|false)',
                        content)
                    direction  = enabled_m.group(1) if enabled_m else 'true'
                    flag_value = c['value']  # 'Agent' or 'Consumer'
                    if direction == 'true':
                        flow_signals.add(flag_value)
                    else:
                        other = 'Consumer' if flag_value == 'Agent' else 'Agent'
                        flow_signals.add(other)
                else:
                    sources.append(c['value'])
            else:
                unknown.append(flag)

        elif flag.startswith('ba_'):
            base = (flag[:-5] if flag.endswith('_True') else
                    (flag[:-6] if flag.endswith('_False') else flag)).strip()
            enabled_m = re.search(
                rf'THE FEATURE "{re.escape(flag)}" IS ENABLED IN features is (true|false)', content)
            condition_result = enabled_m.group(1) if enabled_m else 'unknown'
            known = ba_cfg.get(base, {})

            interp_key     = f"{base}={condition_result}"
            interpretation = interp_cfg.get(interp_key, '')
            always_on      = known.get('always_on')

            if always_on is True:
                fires = (condition_result == 'true')
            elif always_on is False:
                fires = (condition_result == 'false')
            else:
                fires = None

            ba_flags_raw.append({
                'flag_full':        flag,
                'base':             base,
                'condition_result': condition_result,
                'classification':   known.get('classification', 'UNRESOLVED'),
                'always_on':        always_on,
                'fires':            fires,
                'interpretation':   interpretation,
                'reason':           known.get('reason', '')
            })

        else:
            skip_cfg = config.get('skip_flags', {})
            if flag in skip_cfg:
                continue
            unknown.append(flag)

    if 'Agent' in flow_signals and 'Consumer' in flow_signals:
        flow = 'Both'
    elif 'Agent' in flow_signals:
        flow = 'Agent'
    elif 'Consumer' in flow_signals:
        flow = 'Consumer'
    else:
        flow = 'Both'

    return flow, sources, ba_flags_raw, unknown


# ── LOB Extraction ────────────────────────────────────────────────────────────

def extract_lobs(content: str, config: dict) -> tuple:
    lob_map = config.get('lob_map', {})
    includes, excludes = [], []
    for key, code in lob_map.items():
        if f'Lob.{key} !in quoteData.Lobs' in content or f'do not contain {key}' in content:
            excludes.append(code)
        elif f'Lob.{key} in quoteData.Lobs' in content or f'contain {key}' in content:
            includes.append(code)
    return list(set(includes)), list(set(excludes))


# ── Condition Extraction ──────────────────────────────────────────────────────

def extract_conditions(content: str) -> str:
    """
    Extract field conditions verbatim from ORIGINAL_BAL comment block.
    Returns 'true' when no field conditions exist (rule fires unconditionally).

    Two-pass approach:
      Pass 1: strips ODM preamble lines (feature flags, definitions, stage set,
              boilerplate 'if', 'all of the following') — stops at 'then'
      Pass 2: drops standalone boilerplate from remaining lines (bare 'true',
              'and/or true', SET VAR lines)
    """
    bal = re.search(r'<ORIGINAL_BAL(.+?)ORIGINAL_BAL>', content, re.DOTALL)
    if not bal:
        return 'true'

    PREAMBLE_PATTERNS = (
        re.compile(r'isInFeature\('),
        re.compile(r'IS ENABLED IN features is'),
        re.compile(r'^definitions\b'),
        re.compile(r"^set\s+'currentStage'"),
        re.compile(r'^if\s*$'),
        re.compile(r'^(all|one)\s+of\s+the\s+following'),
        re.compile(r'currentStage\s+is\b'),
    )
    raw_lines = []
    in_conditions = False
    for line in bal.group(1).split('\n'):
        clean = re.sub(r'^\s*\*[\s\t]*', '', line).strip()
        clean = re.sub(r'^\\t+', '', clean).strip()
        if not clean:
            continue
        if re.search(r'\bthen\b', clean):
            break
        if clean in (', ,', ',  ,') or clean.startswith('print ') or clean.startswith("'the interview"):
            break
        if not in_conditions:
            if any(p.search(clean) for p in PREAMBLE_PATTERNS):
                continue
            in_conditions = True
        raw_lines.append(clean)

    BOILERPLATE = (
        re.compile(r'^-?\s*true\s*$'),
        re.compile(r'^(and|or)\s+true\s*$'),
        re.compile(r'^SET VAR'),
    )
    cond_lines = [l for l in raw_lines if not any(p.match(l) for p in BOILERPLATE)]

    if not cond_lines:
        return 'true'

    result = ' '.join(cond_lines)
    result = re.sub(r"'the policy data'\s*\.\s*", '', result)
    result = re.sub(r'\s*,\s*,.*$', '', result).strip()
    result = re.sub(r'^(and|or)\s+', '', result).strip()
    return result if result else 'true'


# ── Config Helpers ────────────────────────────────────────────────────────────

def load_config(path: str) -> dict:
    with open(path) as f:
        return json.load(f)

def save_config(config: dict, path: str):
    with open(path, 'w') as f:
        json.dump(config, f, indent=2)
    print(f"Config saved: {path}")


# ── CSV Writer ────────────────────────────────────────────────────────────────

def write_csv(df: pd.DataFrame, path: str):
    df.to_csv(path, index=False, encoding='utf-8-sig')
    print(f"  {os.path.basename(path)}")
